version: "2"
services:
  rocketchat:
    image: cusdeb/rocketchat:6.2-amd64
    networks:
    - rocketchat-network
    environment:
    - PORT=8006
    - MONGO_DATABASE=rocketchat
    - MONGO_HOST=mongo:27017
    - MONGO_OPLOG_HOST=mongo:27017
    - ROOT_URL=http://127.0.0.1:8006
    ports:
    - "8006:8006"
  mongo:
    image: mongo:4.4
    networks:
    - rocketchat-network
    volumes:
    - ./_db:/data/db
    command: mongod --oplogSize 128 --replSet rs0
  mongo-init-replica:
    image: mongo:4.4
    networks:
    - rocketchat-network
    command: >
      bash -c
        "for i in $$(seq 1 30); do
          mongo mongo/rocketchat --eval \"
            rs.initiate({
              _id: 'rs0',
              members: [ { _id: 0, host: 'mongo:27017' } ]})\" &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - mongo
networks:
  rocketchat-network:
    driver: bridge
