version: "3.8"
services:
  mariadb:
    image: cusdeb/mariadb:10.6-amd64
    network_mode: "host"
    environment:
    - MYSQLD_port=${MYSQLD_port}
    - MYSQL_ROOT_PASSWORD=cusdeb
    - MYSQL_DATABASE=
    - MYSQL_USER=
    - MYSQL_PASSWORD=
    volumes:
    - /srv/mysql:/var/lib/mysql
