db:
  image: postgres:13
  restart: always
  environment:
    - POSTGRES_USER=${PG_USER}
    - POSTGRES_DB=${PG_NAME}
    - POSTGRES_PASSWORD=${PG_PASSWORD}
    - PGHOST=${PG_HOST}
    - PGPORT=${PG_PORT}
  volumes:
  - ./volumes/_db:/var/lib/postgresql/data
  net: host

meeseeks:
  image: meeseeks:${TAG}
  restart: always
  net: host
  environment:
    # ----- Meeseeks
    - ALIAS=${ALIAS}
    - COMPANY_NAME=${COMPANY_NAME}
    - CONNECT_ATTEMPTS=${CONNECT_ATTEMPTS}
    - HELLO_RESPONSE=${HELLO_RESPONSE}
    - ROCKET_CHAT_API=${ROCKET_CHAT_API}
    - PASSWORD=${PASSWORD}
    - USER_NAME=${USER_NAME}
    - TIME_ZONE=${TIME_ZONE}
    # ----- Postgres
    - PG_HOST=${PG_HOST}
    - PG_NAME=${PG_NAME}
    - PG_PASSWORD=${PG_PASSWORD}
    - PG_PORT=${PG_PORT}
    - PG_USER=${PG_USER}
    # ----- HappyBirthder
    - BIRTHDAY_CHANNEL_TTL=${BIRTHDAY_CHANNEL_TTL}
    - BIRTHDAY_LOGGING_CHANNEL=${BIRTHDAY_LOGGING_CHANNEL}
    - CHECK_USERS_AVATARS=${CHECK_USERS_AVATARS}
    - CREATE_BIRTHDAY_CHANNELS=${CREATE_BIRTHDAY_CHANNELS}
    - GREETINGS_RESPONSE=${GREETINGS_RESPONSE}
    - HB_CRONTAB=${HB_CRONTAB}
    - NOTIFY_SET_AVATAR=${NOTIFY_SET_AVATAR}
    - NOTIFY_SET_BIRTH_DATE=${NOTIFY_SET_BIRTH_DATE}
    - NUMBER_OF_DAYS_IN_ADVANCE=${NUMBER_OF_DAYS_IN_ADVANCE}
    - PERSONS_WITHOUT_BIRTHDAY_RESPONSE=${PERSONS_WITHOUT_BIRTHDAY_RESPONSE}
    - SET_BIRTHDAY_RESPONSE=${SET_BIRTHDAY_RESPONSE}
    # ----- TenorAPI
    - CONGRATULATION_PHRASES=${CONGRATULATION_PHRASES}
    - TENOR_API_KEY=${TENOR_API_KEY}
    - TENOR_API_URL=${TENOR_API_URL}
    - TENOR_IMAGE_LIMIT=${TENOR_IMAGE_LIMIT}
    - TENOR_SEARCH_TERM=${TENOR_SEARCH_TERM}
    - TENOR_BLACKLISTED_GIF_IDS=${TENOR_BLACKLISTED_GIF_IDS}
    # ----- VoteOrDie
    - RESPOND_TO_DM=${RESPOND_TO_DM}
    # ----- Holidays
    - CUSTOM_HOLIDAYS=${CUSTOM_HOLIDAYS}
    - HOLIDAYS_CRONTAB_WEEK_BEFORE=${HOLIDAYS_CRONTAB_WEEK_BEFORE}
    - HOLIDAYS_CRONTAB_DAY_BEFORE=${HOLIDAYS_CRONTAB_DAY_BEFORE}
    # ----- Reminder
    - REMINDERS_LIST=${REMINDERS_LIST}
